name: CD - Deploy Next.js (artifact)

on:
  workflow_run:
    workflows: [ "CI - Build Next.js (once)" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sale-fe-build

      - name: Copy artifact to server
        run: |
          scp sale-fe.tar.gz \
            dev_01@10.110.20.107:/home/dev_01/sale-fe/

      - name: Extract & restart service
        run: |
          ssh dev_01@10.110.20.107 <<'EOF'
          cd /home/dev_01/sale-fe
          tar -xzf sale-fe.tar.gz
          sudo systemctl restart sale-fe
          EOF
