name: CI/CD - Build & Deploy Next.js

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create env for build
        run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_BE=${{ secrets.NEXT_PUBLIC_BE }}
          EOF

      - name: Build Next.js (standalone)
        run: npm run build

      - name: Deploy standalone (safe)
        run: |
          rsync -av --delete \
            .next/standalone/ \
            /home/dev_01/sale-fe/

          rsync -av \
            .next/static \
            /home/dev_01/sale-fe/.next/

          rsync -av \
            public \
            /home/dev_01/sale-fe/

          rsync -av \
            package.json \
            /home/dev_01/sale-fe/

      - name: Restart service
        run: |
          sudo systemctl restart sale-fe

      - name: Cleanup build artifacts
        run: |
          echo "🧹 Cleaning build artifacts..."
          rm -rf .next
          rm -f .env.local
