name: CI - Build Next.js (once)

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create env for build
        run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_BE=${{ secrets.NEXT_PUBLIC_BE }}
          EOF

      - name: Build Next.js (standalone)
        run: npm run build

      - name: Package build artifact
        run: |
          tar -czf sale-fe.tar.gz \
            .next/standalone \
            .next/static \
            public \
            package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sale-fe-build
          path: sale-fe.tar.gz
